/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as i0 from '@angular/core';
import * as i1 from './router_store_module';
import * as i2 from './serializer';
import * as i3 from '@ngrx/store';
import * as i4 from '@angular/router';
export const StoreRouterConnectingModuleNgFactory:i0.NgModuleFactory<i1.StoreRouterConnectingModule> = i0.ɵcmf(i1.StoreRouterConnectingModule,
    ([] as any[]),(_l:any) => {
      return i0.ɵmod([i0.ɵmpd(512,i0.ComponentFactoryResolver,i0.ɵCodegenComponentFactoryResolver,
          [[8,([] as any[])],[3,i0.ComponentFactoryResolver],i0.NgModuleRef]),i0.ɵmpd(512,
          i2.RouterStateSerializer,i2.DefaultRouterStateSerializer,([] as any[])),
          i0.ɵmpd(256,i1._ROUTER_CONFIG,{stateKey:i1.DEFAULT_ROUTER_FEATURENAME},([] as any[])),
          i0.ɵmpd(1024,i1.ROUTER_CONFIG,i1._createDefaultRouterConfig,[i1._ROUTER_CONFIG]),
          i0.ɵmpd(512,i1.StoreRouterConnectingModule,i1.StoreRouterConnectingModule,
              [i3.Store,i4.Router,i2.RouterStateSerializer,i1.ROUTER_CONFIG])]);
    });
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiQzovUmF1c2hhbi9BTkcyL3BsYXRmb3JtL21vZHVsZXMvcm91dGVyLXN0b3JlL3NyYy9yb3V0ZXJfc3RvcmVfbW9kdWxlLm5nZmFjdG9yeS50cyIsInZlcnNpb24iOjMsInNvdXJjZVJvb3QiOiIiLCJzb3VyY2VzIjpbIm5nOi8vL0M6L1JhdXNoYW4vQU5HMi9wbGF0Zm9ybS9tb2R1bGVzL3JvdXRlci1zdG9yZS9zcmMvcm91dGVyX3N0b3JlX21vZHVsZS50cyJdLCJzb3VyY2VzQ29udGVudCI6WyIgIl0sIm1hcHBpbmdzIjoiQUFBQTs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7OzsifQ==
