/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as i0 from '@angular/core';
import * as i1 from './store_module';
import * as i2 from './actions_subject';
import * as i3 from './reducer_manager';
import * as i4 from './scanned_actions_subject';
import * as i5 from './tokens';
export const StoreRootModuleNgFactory:i0.NgModuleFactory<i1.StoreRootModule> = i0.ɵcmf(i1.StoreRootModule,
    ([] as any[]),(_l:any) => {
      return i0.ɵmod([i0.ɵmpd(512,i0.ComponentFactoryResolver,i0.ɵCodegenComponentFactoryResolver,
          [[8,([] as any[])],[3,i0.ComponentFactoryResolver],i0.NgModuleRef]),i0.ɵmpd(512,
          i1.StoreRootModule,i1.StoreRootModule,[i2.ActionsSubject,i3.ReducerObservable,
              i4.ScannedActionsSubject])]);
    });
export const StoreFeatureModuleNgFactory:i0.NgModuleFactory<i1.StoreFeatureModule> = i0.ɵcmf(i1.StoreFeatureModule,
    ([] as any[]),(_l:any) => {
      return i0.ɵmod([i0.ɵmpd(512,i0.ComponentFactoryResolver,i0.ɵCodegenComponentFactoryResolver,
          [[8,([] as any[])],[3,i0.ComponentFactoryResolver],i0.NgModuleRef]),i0.ɵmpd(131584,
          i1.StoreFeatureModule,i1.StoreFeatureModule,[i5.STORE_FEATURES,i5.FEATURE_REDUCERS,
              i3.ReducerManager])]);
    });
export const StoreModuleNgFactory:i0.NgModuleFactory<i1.StoreModule> = i0.ɵcmf(i1.StoreModule,
    ([] as any[]),(_l:any) => {
      return i0.ɵmod([i0.ɵmpd(512,i0.ComponentFactoryResolver,i0.ɵCodegenComponentFactoryResolver,
          [[8,([] as any[])],[3,i0.ComponentFactoryResolver],i0.NgModuleRef]),i0.ɵmpd(512,
          i1.StoreModule,i1.StoreModule,([] as any[]))]);
    });
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiQzovUmF1c2hhbi9BTkcyL3BsYXRmb3JtL21vZHVsZXMvc3RvcmUvc3JjL3N0b3JlX21vZHVsZS5uZ2ZhY3RvcnkudHMiLCJ2ZXJzaW9uIjozLCJzb3VyY2VSb290IjoiIiwic291cmNlcyI6WyJuZzovLy9DOi9SYXVzaGFuL0FORzIvcGxhdGZvcm0vbW9kdWxlcy9zdG9yZS9zcmMvc3RvcmVfbW9kdWxlLnRzIl0sInNvdXJjZXNDb250ZW50IjpbIiAiXSwibWFwcGluZ3MiOiJBQUFBOzs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7In0=
