/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as i0 from '@angular/core';
import * as i1 from './effects_root_module';
import * as i2 from './effect_sources';
import * as i3 from './effects_runner';
import * as i4 from '@ngrx/store';
import * as i5 from './tokens';
export const EffectsRootModuleNgFactory:i0.NgModuleFactory<i1.EffectsRootModule> = i0.ɵcmf(i1.EffectsRootModule,
    ([] as any[]),(_l:any) => {
      return i0.ɵmod([i0.ɵmpd(512,i0.ComponentFactoryResolver,i0.ɵCodegenComponentFactoryResolver,
          [[8,([] as any[])],[3,i0.ComponentFactoryResolver],i0.NgModuleRef]),i0.ɵmpd(512,
          i1.EffectsRootModule,i1.EffectsRootModule,[i2.EffectSources,i3.EffectsRunner,
              i4.Store,i5.ROOT_EFFECTS,[2,i4.StoreModule]])]);
    });
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiQzovUmF1c2hhbi9BTkcyL3BsYXRmb3JtL21vZHVsZXMvZWZmZWN0cy9zcmMvZWZmZWN0c19yb290X21vZHVsZS5uZ2ZhY3RvcnkudHMiLCJ2ZXJzaW9uIjozLCJzb3VyY2VSb290IjoiIiwic291cmNlcyI6WyJuZzovLy9DOi9SYXVzaGFuL0FORzIvcGxhdGZvcm0vbW9kdWxlcy9lZmZlY3RzL3NyYy9lZmZlY3RzX3Jvb3RfbW9kdWxlLnRzIl0sInNvdXJjZXNDb250ZW50IjpbIiAiXSwibWFwcGluZ3MiOiJBQUFBOzs7Ozs7Ozs7Ozs7Ozs7Ozs7OzsifQ==
