/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as i0 from '@angular/core';
import * as i1 from './effects_feature_module';
import * as i2 from './effects_root_module';
import * as i3 from './tokens';
import * as i4 from '@ngrx/store';
export const EffectsFeatureModuleNgFactory:i0.NgModuleFactory<i1.EffectsFeatureModule> = i0.ɵcmf(i1.EffectsFeatureModule,
    ([] as any[]),(_l:any) => {
      return i0.ɵmod([i0.ɵmpd(512,i0.ComponentFactoryResolver,i0.ɵCodegenComponentFactoryResolver,
          [[8,([] as any[])],[3,i0.ComponentFactoryResolver],i0.NgModuleRef]),i0.ɵmpd(512,
          i1.EffectsFeatureModule,i1.EffectsFeatureModule,[i2.EffectsRootModule,i3.FEATURE_EFFECTS,
              [2,i4.StoreModule]])]);
    });
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiQzovUmF1c2hhbi9BTkcyL3BsYXRmb3JtL21vZHVsZXMvZWZmZWN0cy9zcmMvZWZmZWN0c19mZWF0dXJlX21vZHVsZS5uZ2ZhY3RvcnkudHMiLCJ2ZXJzaW9uIjozLCJzb3VyY2VSb290IjoiIiwic291cmNlcyI6WyJuZzovLy9DOi9SYXVzaGFuL0FORzIvcGxhdGZvcm0vbW9kdWxlcy9lZmZlY3RzL3NyYy9lZmZlY3RzX2ZlYXR1cmVfbW9kdWxlLnRzIl0sInNvdXJjZXNDb250ZW50IjpbIiAiXSwibWFwcGluZ3MiOiJBQUFBOzs7Ozs7Ozs7Ozs7Ozs7Ozs7OyJ9
